### ISSUE TITLE
Add ability to castle

### ISSUE THREAD

**Issue by 5465869** [5465869/typescript-react-chess#2]
This will likely need some unit tests to verify that this works. 

The rules for castling according to the internet : 
  - castling is only possible if neither the king nor the rook has moved
  - there must not be any pieces between the king and the rook
  - the king may not be in check
  - the square the king goes to and any intervening squares may not be under attack
  - however, there is nothing to prevent castling if the rook is under attack

https://learn.chessbase.com/en/page/chess-rules-castling?setssocookie=eVSEJkg4HQR%2fdz5TCwmcTFg93m9K7%2bv31ta9afX9%2bMA%3d

**Comment by jackjiang871** [comment]
Currently working on a solution
